global_costmap:
  global_frame: map
  robot_base_frame: base_link
  width: 100.0
  height: 100.0
  origin_x: -50.0
  origin_y: -50.0
  update_frequency: 5.0
  static_map: false
  plugins:
  - {name: rgbd_obstacle_layer, type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
